#!/bin/bash
# One-shot tillicum env setup for lingbot-va LIBERO-Plus eval.
#
# Creates a fresh conda env at $MINIFORGE_ROOT/envs/$ENV_NAME with the
# pinned deps from lingbot-va README + LIBERO-plus + huggingface-cli, then
# writes /gpfs/home/jliu63/activate_lingbot_va_tillicum.sh so the eval slurm
# can `source` it.
#
# Idempotent: re-running skips work that's already done.
#
# Usage:
#   bash scripts/setup_lingbot_va_tillicum.sh
#
# After this finishes, sanity-check with:
#   source /gpfs/home/jliu63/activate_lingbot_va_tillicum.sh
#   python -c "import torch, diffusers, libero; print(torch.__version__, diffusers.__version__)"
#   python -c "from libero.libero import benchmark; print(list(benchmark.get_benchmark_dict().keys()))"

set -euo pipefail

# Auto-detect miniforge root from the conda already on PATH (so we don't
# hard-code a path that drifts from the user's actual install). Override
# via MINIFORGE_ROOT env var if needed.
if [[ -z "${MINIFORGE_ROOT:-}" ]]; then
  CONDA_BIN="$(command -v conda || true)"
  if [[ -z "$CONDA_BIN" ]]; then
    echo "ERROR: no conda on PATH and MINIFORGE_ROOT not set" >&2
    exit 1
  fi
  # conda lives at $ROOT/bin/conda or $ROOT/condabin/conda; both yield $ROOT
  # via two dirname's.
  MINIFORGE_ROOT="$(dirname "$(dirname "$CONDA_BIN")")"
  echo "[setup] auto-detected MINIFORGE_ROOT=$MINIFORGE_ROOT"
fi

ENV_NAME="${ENV_NAME:-lingbot_va_libero}"
ACTIVATE_SCRIPT="${ACTIVATE_SCRIPT:-/gpfs/home/jliu63/activate_lingbot_va_tillicum.sh}"
LIBERO_PLUS_ROOT="${LIBERO_PLUS_ROOT:-/gpfs/home/jliu63/projects/HVLA/third_party/LIBERO-plus}"

[[ -d "$MINIFORGE_ROOT" ]] || { echo "ERROR: MINIFORGE_ROOT=$MINIFORGE_ROOT not found"; exit 1; }
[[ -f "$MINIFORGE_ROOT/etc/profile.d/conda.sh" ]] || {
  echo "ERROR: $MINIFORGE_ROOT/etc/profile.d/conda.sh missing — wrong MINIFORGE_ROOT?"; exit 1;
}
source "$MINIFORGE_ROOT/etc/profile.d/conda.sh"

# ── 1. Create env if missing ─────────────────────────────────────────────────
if ! conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
  echo "[setup] creating conda env $ENV_NAME (python=3.10.16)"
  conda create -y -n "$ENV_NAME" python=3.10.16
else
  echo "[setup] env $ENV_NAME already exists"
fi

conda activate "$ENV_NAME"

# ── 2. Install pinned deps from lingbot-va README ────────────────────────────
echo "[setup] installing torch 2.9.0 + cu126"
pip install --upgrade pip
pip install --quiet torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0 \
    --index-url https://download.pytorch.org/whl/cu126

echo "[setup] installing lingbot-va runtime deps"
pip install --quiet \
    websockets einops diffusers==0.36.0 transformers==4.55.2 accelerate \
    msgpack opencv-python matplotlib ftfy easydict \
    huggingface_hub

# flash-attn is OPTIONAL for inference: lingbot-va's attn_mode='torch' (SDPA)
# path doesn't call flash_attn_func, and our launch_server.sh patches the
# released ckpt to attn_mode=torch. wan_va/modules/model.py defers the
# ImportError until attn_mode='flashattn' is actually selected, so a missing
# flash-attn is fine for our LIBERO-Plus eval.
#
# Building flash-attn from source needs nvcc + CUDA_HOME (cluster `module
# load cuda/12.x`), which most login nodes don't have by default. Skip by
# default; opt in by setting INSTALL_FLASH_ATTN=1.
if [[ "${INSTALL_FLASH_ATTN:-0}" == "1" ]]; then
  echo "[setup] installing flash-attn (no-build-isolation, ~30 min build)"
  pip install --quiet flash-attn --no-build-isolation || {
    echo "[setup] WARN: flash-attn install failed — eval still works with attn_mode=torch"
  }
else
  echo "[setup] SKIPPING flash-attn (set INSTALL_FLASH_ATTN=1 to enable). "
  echo "        Inference uses attn_mode=torch (SDPA) which doesn't need it."
fi

# Required for the eval client to read LeRobot helpers + write_json
echo "[setup] installing lerobot==0.3.3 + scipy (no-deps; lerobot pulls heavy stuff otherwise)"
pip install --quiet lerobot==0.3.3 scipy --no-deps

# ── 3. LIBERO-plus (sim) deps ────────────────────────────────────────────────
# LIBERO-plus's setup.py installs robosuite/mujoco/etc. We don't `pip install
# -e` the package because our slurm puts it on PYTHONPATH directly; we just
# need its third-party requirements.
if [[ -f "$LIBERO_PLUS_ROOT/requirements.txt" ]]; then
  echo "[setup] installing LIBERO-plus requirements"
  pip install --quiet -r "$LIBERO_PLUS_ROOT/requirements.txt" || {
    echo "[setup] WARN: some LIBERO-plus deps failed; you may need to fix manually"
  }
else
  echo "[setup] WARN: $LIBERO_PLUS_ROOT/requirements.txt not found — LIBERO sim deps NOT installed"
  echo "         Either fix LIBERO_PLUS_ROOT or install LIBERO/robosuite manually."
fi

# ── 4. Write the activate script ─────────────────────────────────────────────
mkdir -p "$(dirname "$ACTIVATE_SCRIPT")"
cat > "$ACTIVATE_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by lingbot-va/scripts/setup_lingbot_va_tillicum.sh
# Source this before running lingbot-va LIBERO-Plus eval on tillicum.
source "$MINIFORGE_ROOT/etc/profile.d/conda.sh"
conda activate "$ENV_NAME"
EOF
chmod +x "$ACTIVATE_SCRIPT"
echo "[setup] wrote activate script → $ACTIVATE_SCRIPT"

echo ""
echo "[setup] DONE. Verify with:"
echo "  source $ACTIVATE_SCRIPT"
echo "  python -c 'import torch, diffusers; print(torch.__version__, diffusers.__version__)'"
echo "  python -c 'from libero.libero import benchmark; print(list(benchmark.get_benchmark_dict().keys()))'"
